project:
  type: website
  output-dir: .
  render:
    - "*.qmd"
    - "programa/*.qmd"
    - "giras/*.qmd"
    - "labs/*.qmd"
    - "lectures/*.qmd"
    - "refs/*.qmd"
    - "!exams/**"

quarto-required: ">=1.4.0"

filters:
  - filters/answer-space.lua

website:
  title: "Laboratorio de Ecologia General B-0305"
  navbar:
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Programa"
        href: programa/index.qmd
      - text: "Clases"
        href: lectures/index.qmd
      - text: "Laboratorios"
        href: labs/index.qmd
      - text: "Referencias"
        href: refs/index.qmd
      # - text: "Giras"
      #   href: giras/index.qmd