---
title: "Referencias"
---

## Hypothesis y Predicciones

- [Farji-Brener 2003](Farji-Brener-2003.pdf)
- [Farji-Brener 2004](Farji-Brener-2004.pdf)
- [Gotelli 2004, cap. 4](Gotelli-2004-cap-4.pdf)

## Deseño Experimental

- [Gotelli 2004, cap. 6](Gotelli-2004-cap-6.pdf)
- [Marshall 2024](Marshall-2024.pdf)

## Analisis de Datos Exploratorio

Con `R`:

- [Wickham et al. R for Data Science, 2ed.](https://r4ds.hadley.nz/)

  Especificamente:

  - [Capitulo 1](https://r4ds.hadley.nz/data-visualize.html)
  - [Capitulo 10](https://r4ds.hadley.nz/EDA.html)

Con `Python`:

- [Think Stats](https://allendowney.github.io/ThinkStats/)

  Especificamente:

  - [Capitulo 1](https://allendowney.github.io/ThinkStats/chap01.html)
  - [Capitulo 2](https://allendowney.github.io/ThinkStats/chap02.html)

## Modelos Lineales Generalizados (GLM)

Libro sobre GLMs de Quebec Centre for Biodiversity Science con ejemplos en `R` para datos binarios, proporciones y conteos:

  - [QCBS R Workshop Series, 2024](https://r.qcbs.ca/workshop06/book-en/binomial-glm.html)

Articulos:

Datos de conteo (Poisson, Quasi-poisson, Binomial Negativa):

  - [O'Hara & Kotze, 2010](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/j.2041-210X.2010.00021.x)  
  - [Warton et al. 2016](https://besjournals.onlinelibrary.wiley.com/doi/10.1111/2041-210X.12552)  

Web app:

  Web app para simular conteos con diferentes parametros (varianza, probabilidad de zeros) y
  ver como datos simulados comparan con lo que espera la distribucion Poisson.

  - [https://diatom.shinyapps.io/B0305/](https://diatom.shinyapps.io/B0305/)