<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Lab 04: Modelos lineales – Laboratorio de Ecologia General B-0305</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-38566f2d191bdb59836365460af85d63.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Sin resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Laboratorio de Ecologia General B-0305</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Buscar"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Navegación de palanca" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Inicio</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../programa/index.html"> 
<span class="menu-text">Programa</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../lectures/index.html"> 
<span class="menu-text">Clases</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../labs/index.html"> 
<span class="menu-text">Laboratorios</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../refs/index.html"> 
<span class="menu-text">Referencias</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En esta página</h2>
   
  <ul>
  <li><a href="#actividad" id="toc-actividad" class="nav-link active" data-scroll-target="#actividad">Actividad</a></li>
  <li><a href="#material" id="toc-material" class="nav-link" data-scroll-target="#material">Material</a></li>
  <li><a href="#conceptos-básicos-de-regresión-lineal-todos" id="toc-conceptos-básicos-de-regresión-lineal-todos" class="nav-link" data-scroll-target="#conceptos-básicos-de-regresión-lineal-todos">Conceptos básicos de regresión lineal (todos)</a></li>
  <li><a href="#resumen-de-un-modelo-lineal-con-un-predictor-continuo-experto-1" id="toc-resumen-de-un-modelo-lineal-con-un-predictor-continuo-experto-1" class="nav-link" data-scroll-target="#resumen-de-un-modelo-lineal-con-un-predictor-continuo-experto-1">Resumen de un modelo lineal con un predictor continuo (experto 1)</a></li>
  <li><a href="#resumen-de-un-modelo-lineal-con-un-predictor-categórico-experto-2" id="toc-resumen-de-un-modelo-lineal-con-un-predictor-categórico-experto-2" class="nav-link" data-scroll-target="#resumen-de-un-modelo-lineal-con-un-predictor-categórico-experto-2">Resumen de un modelo lineal con un predictor categórico (experto 2)</a></li>
  <li><a href="#resumen-summary-de-un-modelo-lineal-con-dos-predictores-y-su-interacción-experto-3" id="toc-resumen-summary-de-un-modelo-lineal-con-dos-predictores-y-su-interacción-experto-3" class="nav-link" data-scroll-target="#resumen-summary-de-un-modelo-lineal-con-dos-predictores-y-su-interacción-experto-3">Resumen (<code>summary()</code>) de un modelo lineal con dos predictores y su interacción (experto 3)</a></li>
  <li><a href="#diagnósticos-gráficos-i-linealidad-y-normalidad-experto-4" id="toc-diagnósticos-gráficos-i-linealidad-y-normalidad-experto-4" class="nav-link" data-scroll-target="#diagnósticos-gráficos-i-linealidad-y-normalidad-experto-4">Diagnósticos gráficos I: linealidad y normalidad (experto 4)</a></li>
  <li><a href="#diagnósticos-gráficos-ii-varianza-y-observaciones-influyentes-experto-5" id="toc-diagnósticos-gráficos-ii-varianza-y-observaciones-influyentes-experto-5" class="nav-link" data-scroll-target="#diagnósticos-gráficos-ii-varianza-y-observaciones-influyentes-experto-5">Diagnósticos gráficos II: varianza y observaciones influyentes (experto 5)</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Otros formatos</h2><ul><li><a href="L04-actividad-1-lm.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Lab 04: Modelos lineales</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Código</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="actividad" class="level2">
<h2 class="anchored" data-anchor-id="actividad">Actividad</h2>
<div class="callout callout-style-default callout-note callout-titled" title="Fase 1: Aprendizaje independiente en su grupo original (5 minutos)">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Fase 1: Aprendizaje independiente en su grupo original (5 minutos)
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Nos dividimos en grupos de 5 personas.</li>
<li>Todo el grupo repasa junto los conceptos básicos de regresión lineal (sección común del material).</li>
<li>Cada grupo tiene además un experto para la salida de un modelo lineal:
<ol type="1">
<li>con predictor continuo</li>
<li>con predictor categórico</li>
<li>con interacción (continuo × categórico)</li>
<li>diagnósticos I: linealidad y normalidad</li>
<li>diagnósticos II: varianza y observaciones influyentes</li>
</ol></li>
<li>El experto estudia el material sobre su tema específico.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Fase 2: Aprendizaje colaborativo en grupos de expertos (5 + 2 minutos)">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Fase 2: Aprendizaje colaborativo en grupos de expertos (5 + 2 minutos)
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Los expertos de cada tema se reúnen en grupos para compartir sus conocimientos.</li>
<li>Aclaran dudas entre expertos, toman notas y se preparan para enseñar a su grupo original.</li>
<li>El experto prepara un reporte breve de 3 puntos:
<ol type="1">
<li>¿Cuál es la pregunta que este análisis permite contestar?</li>
<li>¿Qué parte de la salida hay que mirar para contestarla?</li>
<li>¿Cómo explicaría el resultado en lenguaje biológico, sin usar lenguaje estadístico?</li>
</ol></li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Fase 3: Enseñanza en el grupo original (2 x 5 minutos)">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Fase 3: Enseñanza en el grupo original (2 x 5 minutos)
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Cada experto regresa a su grupo original y enseña a los demás miembros del grupo sobre su tema.</li>
<li>Se discuten y resuelven dudas sobre los temas presentados por los expertos.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Fase 4: Reflexión y cierre (5 minutos)">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Fase 4: Reflexión y cierre (5 minutos)
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Se comparten conclusiones y se resuelven dudas finales con toda la clase.</li>
<li>Cada grupo original (no grupo de expertos) tiene que resolver la tarea de la ultima página (caja roja).</li>
</ul>
</div>
</div>
<p><strong>El reporte de Fase 2, escrito en su bitacora, representa su entrada de bitacora calificada</strong></p>
<div style="page-break-after: always;"></div>
</section>
<section id="material" class="level2">
<h2 class="anchored" data-anchor-id="material">Material</h2>
<p>En lo que sigue se presentan los conceptos básicos de los modelos lineales (<code>lm()</code>) y cómo interpretar su salida. Todos los ejemplos usan el dataset <code>iris</code>, incluido con <code>R</code>.</p>
</section>
<section id="conceptos-básicos-de-regresión-lineal-todos" class="level2">
<h2 class="anchored" data-anchor-id="conceptos-básicos-de-regresión-lineal-todos">Conceptos básicos de regresión lineal (todos)</h2>
<p>Un modelo lineal describe una variable respuesta continua (<code>y</code>) en función de uno o más predictores (<code>x</code>):</p>
<ul>
<li>Los predictores pueden ser <strong>continuos</strong> (una pendiente) o <strong>categóricos</strong> (diferencias entre grupos).</li>
<li><code>lm()</code> ajusta el modelo; <code>summary()</code> muestra los coeficientes estimados, su incertidumbre y pruebas asociadas.</li>
<li>Supuestos del modelo:
<ul>
<li>relación lineal – la relación entre los predictores y la respuesta debe ser aproximadamente lineal.<br>
</li>
<li>residuos normales – los residuos del modelo deben seguir aproximadamente una distribución normal.<br>
</li>
<li>varianza constante (homocedasticidad) – la dispersión de los residuos debe ser similar a lo largo de todos los valores predichos.<br>
</li>
<li>independencia – los residuos deben ser independientes entre sí, sin correlación.</li>
</ul></li>
</ul>
<div class="sourceCode" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x, <span class="at">data =</span> datos)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><code>y</code>: variable respuesta del modelo.</li>
<li><code>x</code>: predictor del modelo; puede haber cualquier número de predictores, continuos o categóricos.</li>
<li>Los predictores se combinan con <code>+</code> para incluirlos de manera aditiva en el modelo.</li>
<li>Con <code>+</code>, el modelo incluye los efectos de los predictores de manera aditiva, sin términos de interacción.</li>
<li>Para incluir interacciones entre predictores, se usa <code>*</code> (por ejemplo, <code>x1 * x2</code>). En este caso el modelo considera tanto los efectos principales como la interacción entre <code>x1</code> y <code>x2</code>.</li>
<li>La interacción permite que el efecto de un predictor dependa del valor de otro predictor.</li>
</ul>
<div style="page-break-after: always;"></div>
</section>
<section id="resumen-de-un-modelo-lineal-con-un-predictor-continuo-experto-1" class="level2">
<h2 class="anchored" data-anchor-id="resumen-de-un-modelo-lineal-con-un-predictor-continuo-experto-1">Resumen de un modelo lineal con un predictor continuo (experto 1)</h2>
<div class="sourceCode" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>modelo_continuo <span class="ot">&lt;-</span> <span class="fu">lm</span>(Petal.Length <span class="sc">~</span> Sepal.Length, <span class="at">data =</span> iris)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><strong>Estimate</strong> (<code>(Intercept)</code> y pendiente): valor esperado de <code>y</code> cuando <code>x = 0</code>, y cambio en <code>y</code> por cada unidad de <code>x</code>.</li>
<li><strong>Std. Error / t value / Pr(&gt;|t|)</strong>: incertidumbre del coeficiente y prueba de si es diferente de cero.</li>
<li><strong>R² / R² ajustado</strong>: proporción de la varianza de <code>y</code> explicada por el modelo.</li>
<li><strong>F-statistic y su p-value</strong>: prueba si el modelo en conjunto explica más que el modelo nulo (solo el intercepto).</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Petal.Length ~ Sepal.Length, data = iris)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.47747 -0.59072 -0.00668  0.60484  2.49512 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -7.10144    0.50666  -14.02   &lt;2e-16 ***
Sepal.Length  1.85843    0.08586   21.65   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.8678 on 148 degrees of freedom
Multiple R-squared:   0.76, Adjusted R-squared:  0.7583 
F-statistic: 468.6 on 1 and 148 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Como calcular la ecuación del modelo y intervalos de confianza">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Como calcular la ecuación del modelo y intervalos de confianza
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math display">\[
\quad y = \text{intercept} + \text{coef(Sepal.Length)} \cdot x = -7.1014 + 1.8584x
\]</span></p>
<p>Los intervalos de confianza proporcionan un rango de valores plausibles para cada coeficiente del modelo. Si un intervalo incluye el valor cero, sugiere que el coeficiente podría no ser significativamente diferente de cero. Se pueden calcular con:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(modelo_continuo)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
<section id="resumen-de-un-modelo-lineal-con-un-predictor-categórico-experto-2" class="level2">
<h2 class="anchored" data-anchor-id="resumen-de-un-modelo-lineal-con-un-predictor-categórico-experto-2">Resumen de un modelo lineal con un predictor categórico (experto 2)</h2>
<div class="sourceCode" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>modelo_categorico <span class="ot">&lt;-</span> <span class="fu">lm</span>(Petal.Length <span class="sc">~</span> Species, <span class="at">data =</span> iris)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li>R utiliza el <strong>primer nivel del factor</strong> como nivel de referencia (en <code>iris</code>, <code>setosa</code>), que queda absorbido en el <code>(Intercept)</code>.</li>
<li><strong><code>(Intercept)</code></strong>: valor promedio de <code>y</code> para el nivel de referencia.</li>
<li><strong>Coeficientes de los otros niveles</strong>: diferencia promedio respecto al nivel de referencia, no el valor absoluto del grupo.</li>
<li><strong>R² / F-statistic</strong>: mismos conceptos que con predictor continuo, aplicados a la comparación entre grupos.</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Petal.Length ~ Species, data = iris)

Residuals:
   Min     1Q Median     3Q    Max 
-1.260 -0.258  0.038  0.240  1.348 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        1.46200    0.06086   24.02   &lt;2e-16 ***
Speciesversicolor  2.79800    0.08607   32.51   &lt;2e-16 ***
Speciesvirginica   4.09000    0.08607   47.52   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4303 on 147 degrees of freedom
Multiple R-squared:  0.9414,    Adjusted R-squared:  0.9406 
F-statistic:  1180 on 2 and 147 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Como calcular el promedio de cada nivel">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Como calcular el promedio de cada nivel
</div>
</div>
<div class="callout-body-container callout-body">
<p><em>setosa</em>: <span class="math display">\[ \quad \bar{y} = \text{intercept} = 1.462 \]</span></p>
<p><em>versicolor</em>: <span class="math display">\[ \quad \bar{y} = \text{intercept} + \text{coef(versicolor)} = 1.462 + 2.798 = 4.260 \]</span></p>
<p><em>virginica</em>: <span class="math display">\[ \quad \bar{y} = \text{intercept} + \text{coef(virginica)} = 1.462 + 4.090 = 5.552 \]</span></p>
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
<section id="resumen-summary-de-un-modelo-lineal-con-dos-predictores-y-su-interacción-experto-3" class="level2">
<h2 class="anchored" data-anchor-id="resumen-summary-de-un-modelo-lineal-con-dos-predictores-y-su-interacción-experto-3">Resumen (<code>summary()</code>) de un modelo lineal con dos predictores y su interacción (experto 3)</h2>
<div class="sourceCode" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>modelo_interaccion <span class="ot">&lt;-</span> <span class="fu">lm</span>(Petal.Length <span class="sc">~</span> Sepal.Length <span class="sc">*</span> Species, <span class="at">data =</span> iris)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><code>(Intercept)</code>: intercepto del nivel de referencia (setosa).</li>
<li><code>Sepal.Length</code>: pendiente para el nivel de referencia.</li>
<li><code>Speciesversicolor</code>, <code>Speciesvirginica</code>: diferencias en el intercepto respecto al nivel de referencia.</li>
<li><code>Términos de interacción</code>: diferencias en la pendiente respecto al nivel de referencia.</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Petal.Length ~ Sepal.Length * Species, data = iris)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.68611 -0.13442 -0.00856  0.15966  0.79607 

Coefficients:
                               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                      0.8031     0.5310   1.512    0.133    
Sepal.Length                     0.1316     0.1058   1.244    0.216    
Speciesversicolor               -0.6179     0.6837  -0.904    0.368    
Speciesvirginica                -0.1926     0.6578  -0.293    0.770    
Sepal.Length:Speciesversicolor   0.5548     0.1281   4.330 2.78e-05 ***
Sepal.Length:Speciesvirginica    0.6184     0.1210   5.111 1.00e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2611 on 144 degrees of freedom
Multiple R-squared:  0.9789,    Adjusted R-squared:  0.9781 
F-statistic:  1333 on 5 and 144 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Como calcular los efectos de cada nivel de la interacción">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Como calcular los efectos de cada nivel de la interacción
</div>
</div>
<div class="callout-body-container callout-body">
<p><em>setosa</em>: <span class="math display">\[ \quad y_{\text{setosa}}=\text{intercept}+\text{coef(Sepal.Length)}\cdot x \]</span> <!-- $$ \quad y=0.8031+0.1316x $$ --></p>
<p><em>versicolor</em>: <span class="math display">\[
\begin{aligned}
\quad y &amp;= \text{intercept}+\text{coef(versicolor)}+ \\
&amp;\quad \big(\text{coef(Sepal.Length)}+\text{coef(Sepal.Length:Speciesversicolor)}\big)\cdot x
\end{aligned}
\]</span> <!-- $$ \quad y = (0.8031-0.6179) + (0.1316+0.5548)x $$ --></p>
<p><em>virginica</em>: <span class="math display">\[\begin{aligned}
\quad y &amp;= \text{intercept}+\text{coef(virginica)}+ \\
&amp;\quad \big(\text{coef(Sepal.Length)}+\text{coef(Sepal.Length:Speciesvirginica)}\big)\cdot x
\end{aligned}\]</span> <!-- $$\quad y = (0.8031-0.1926) + (0.1316+0.6184)x $$ --></p>
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
<section id="diagnósticos-gráficos-i-linealidad-y-normalidad-experto-4" class="level2">
<h2 class="anchored" data-anchor-id="diagnósticos-gráficos-i-linealidad-y-normalidad-experto-4">Diagnósticos gráficos I: linealidad y normalidad (experto 4)</h2>
<div class="sourceCode" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(modelo_interaccion, <span class="at">which =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><strong>Residuals vs Fitted</strong>: busca patrones o curvatura; una nube sin forma clara indica que la relación es razonablemente lineal.</li>
<li><strong>Normal Q-Q</strong>: los puntos deben seguir aproximadamente la línea diagonal; desviaciones fuertes en los extremos sugieren residuos no normales.</li>
<li>Juntos, estos dos gráficos dicen si un modelo lineal es una descripción razonable de los datos.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="L04-actividad-1-lm_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="864"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Mas info">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Mas info
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Residuals vs Fitted</strong></p>
<p>Los residuos deberían distribuirse de manera aleatoria alrededor de cero. Algun patron sistemático indica que el modelo puede no estar capturando toda la estructura de los datos. Por ejemplo, un patrón en forma de “banano” sugiere que falta una transformación (por ejemplo, logarítmica) o un término no lineal.</p>
<p><strong>Normal Q-Q</strong></p>
<p>Con muestras grandes, el modelo lineal es bastante robusto a desviaciones leves de normalidad, así que un Q-Q plot “casi” recto, aunque no perfecto, muchas veces suele bastar. i.e., muchas veces no es necesario ‘hacer algo’ para para que todos los residuos quedan perfectamente en la línea.</p>
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
<section id="diagnósticos-gráficos-ii-varianza-y-observaciones-influyentes-experto-5" class="level2">
<h2 class="anchored" data-anchor-id="diagnósticos-gráficos-ii-varianza-y-observaciones-influyentes-experto-5">Diagnósticos gráficos II: varianza y observaciones influyentes (experto 5)</h2>
<div class="sourceCode" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(modelo_interaccion, <span class="at">which =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">5</span>))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><strong>Scale-Location</strong>: la línea debería ser aproximadamente horizontal, con dispersión pareja; una forma de embudo indica que la varianza no es constante (heterocedasticidad).</li>
<li><strong>Residuals vs Leverage</strong>: identifica observaciones con mucha influencia sobre el modelo; puntos con una distancia de Cook alta pueden tener una influencia importante sobre los coeficientes del modelo.</li>
<li>Estos dos gráficos ayudan a decidir si algunas observaciones particulares merecen atención (errores de datos, casos atípicos reales).</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="L04-actividad-1-lm_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="864"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Mas info">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Mas info
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Distancia cook</strong></p>
<p>La distancia de Cook depende de los valores de leverage y de los residuos de cada observación. Una distancia de Cook alta indica que la observación puede tener una influencia importante sobre los coeficientes del modelo.</p>
<p>Las líneas punteadas de distancia de Cook solo se dibujan si caen dentro del rango visible del gráfico. Si las líneas de referencia de Cook quedan fuera del rango del gráfico, pueden no aparecer; esto no indica un error del gráfico.</p>
</div>
</div>
<div style="page-break-after: always;"></div>
<div class="callout callout-style-default callout-important callout-titled" title="Tarea (Fase 4)">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tarea (Fase 4)
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Cada grupo original (no grupo de expertos) analiza los mismos datos <code>iris</code> en su computadora.</strong></p>
<blockquote class="blockquote">
<p>Pregunta biológica: ¿cómo cambia el ancho del pétalo con el ancho del sépalo y ese cambio es distinto entre especies?</p>
</blockquote>
<blockquote class="blockquote">
<p>Ajusten * un modelo con interceptos diferentes entre especies y una pendiente común para todas las especies, y * otro que permita intercepto y pendiente distinta por especie.</p>
</blockquote>
<blockquote class="blockquote">
<p>Extraigan los coeficientes y sus intervalos de confianza. Comparen los modelos con AIC e interpreten los resultados.</p>
</blockquote>
<blockquote class="blockquote">
<p>Tareas:</p>
<ul>
<li>Ajusten los dos modelos y comparen sus valores de AIC.</li>
<li>Usen <code>coef()</code> y <code>confint()</code> para identificar el tamaño y la incertidumbre de los efectos de <code>Sepal.Width</code>, de las especies y de los términos de interacción.</li>
<li>En el modelo con interacción, los coeficientes de especie representan diferencias en el intercepto cuando <code>Sepal.Width = 0</code>.</li>
<li>Escriban un párrafo que responda la pregunta biológica. Describan la dirección y magnitud de los efectos, e indiquen los intervalos de confianza.</li>
<li>Usen los <em>p-values</em> solo como información complementaria. La interpretación principal debe basarse en los tamaños de efecto, sus intervalos de confianza y el apoyo relativo de los modelos según AIC.</li>
</ul>
</blockquote>
<blockquote class="blockquote">
<p>Para el análisis, usen <code>lm()</code>, <code>summary()</code>, <code>coef()</code>, <code>confint()</code> y <code>AIC()</code>.</p>
</blockquote>
<blockquote class="blockquote">
<p>Nota: un AIC menor indica un mejor balance entre ajuste y complejidad. Modelos con valores de AIC muy similares (por ejemplo, <span class="math inline">\(\Delta\mathrm{AIC} &lt; 2\)</span>) suelen tener apoyo comparable; diferencias mayores favorecen al modelo con el menor AIC.</p>
</blockquote>
</div>
</div>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Ejecutar el código</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb11" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Lab 04: Modelos lineales"</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="an">subtitle:</span><span class="co"> ""</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="co">    number-sections: false</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="co">  pdf:</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="co">    documentclass: scrartcl      # KOMA-Script class</span></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="co">    classoption: [DIV=12]</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="co">    geometry: margin=1in</span></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a><span class="co">    fontfamily: libertinus        # LaTeX font package</span></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a><span class="co">    colorlinks: true</span></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a><span class="co">    linkcolor: blue</span></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: false</span></span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a><span class="co">    highlight-style: github        # code block theme</span></span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a><span class="co">    title-block-banner: true       # colored title banner</span></span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a><span class="an">lang:</span><span class="co"> es</span></span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a><span class="co">#| include: false</span></span>
<span id="cb11-26"><a href="#cb11-26" aria-hidden="true" tabindex="-1"></a>modelo_continuo <span class="ot">&lt;-</span> <span class="fu">lm</span>(Petal.Length <span class="sc">~</span> Sepal.Length, <span class="at">data =</span> iris)</span>
<span id="cb11-27"><a href="#cb11-27" aria-hidden="true" tabindex="-1"></a>modelo_categorico <span class="ot">&lt;-</span> <span class="fu">lm</span>(Petal.Length <span class="sc">~</span> Species, <span class="at">data =</span> iris)</span>
<span id="cb11-28"><a href="#cb11-28" aria-hidden="true" tabindex="-1"></a>modelo_interaccion <span class="ot">&lt;-</span> <span class="fu">lm</span>(Petal.Length <span class="sc">~</span> Sepal.Length <span class="sc">*</span> Species, <span class="at">data =</span> iris)</span>
<span id="cb11-29"><a href="#cb11-29" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-30"><a href="#cb11-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-31"><a href="#cb11-31" aria-hidden="true" tabindex="-1"></a><span class="fu">## Actividad</span></span>
<span id="cb11-32"><a href="#cb11-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-33"><a href="#cb11-33" aria-hidden="true" tabindex="-1"></a><span class="in">```{=latex}</span></span>
<span id="cb11-34"><a href="#cb11-34" aria-hidden="true" tabindex="-1"></a><span class="in">\footnotesize</span></span>
<span id="cb11-35"><a href="#cb11-35" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-36"><a href="#cb11-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-37"><a href="#cb11-37" aria-hidden="true" tabindex="-1"></a>::: {.callout-note title="Fase 1: Aprendizaje independiente en su grupo original (5 minutos)"}</span>
<span id="cb11-38"><a href="#cb11-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-39"><a href="#cb11-39" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>Nos dividimos en grupos de 5 personas.</span>
<span id="cb11-40"><a href="#cb11-40" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>Todo el grupo repasa junto los conceptos básicos de regresión lineal (sección común del material).</span>
<span id="cb11-41"><a href="#cb11-41" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>Cada grupo tiene además un experto para la salida de un modelo lineal:</span>
<span id="cb11-42"><a href="#cb11-42" aria-hidden="true" tabindex="-1"></a><span class="ss">    1. </span>con predictor continuo</span>
<span id="cb11-43"><a href="#cb11-43" aria-hidden="true" tabindex="-1"></a><span class="ss">    2. </span>con predictor categórico</span>
<span id="cb11-44"><a href="#cb11-44" aria-hidden="true" tabindex="-1"></a><span class="ss">    3. </span>con interacción (continuo × categórico)</span>
<span id="cb11-45"><a href="#cb11-45" aria-hidden="true" tabindex="-1"></a><span class="ss">    4. </span>diagnósticos I: linealidad y normalidad</span>
<span id="cb11-46"><a href="#cb11-46" aria-hidden="true" tabindex="-1"></a><span class="ss">    5. </span>diagnósticos II: varianza y observaciones influyentes</span>
<span id="cb11-47"><a href="#cb11-47" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>El experto estudia el material sobre su tema específico.</span>
<span id="cb11-48"><a href="#cb11-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-49"><a href="#cb11-49" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb11-50"><a href="#cb11-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-51"><a href="#cb11-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-52"><a href="#cb11-52" aria-hidden="true" tabindex="-1"></a>::: {.callout-note title="Fase 2: Aprendizaje colaborativo en grupos de expertos (5 + 2 minutos)"}</span>
<span id="cb11-53"><a href="#cb11-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-54"><a href="#cb11-54" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>Los expertos de cada tema se reúnen en grupos para compartir sus conocimientos.</span>
<span id="cb11-55"><a href="#cb11-55" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>Aclaran dudas entre expertos, toman notas y se preparan para enseñar a su grupo original.</span>
<span id="cb11-56"><a href="#cb11-56" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>El experto prepara un reporte breve de 3 puntos:</span>
<span id="cb11-57"><a href="#cb11-57" aria-hidden="true" tabindex="-1"></a><span class="ss">     1. </span>¿Cuál es la pregunta que este análisis permite contestar?</span>
<span id="cb11-58"><a href="#cb11-58" aria-hidden="true" tabindex="-1"></a><span class="ss">     2. </span>¿Qué parte de la salida hay que mirar para contestarla?</span>
<span id="cb11-59"><a href="#cb11-59" aria-hidden="true" tabindex="-1"></a><span class="ss">     3. </span>¿Cómo explicaría el resultado en lenguaje biológico, sin usar lenguaje estadístico?</span>
<span id="cb11-60"><a href="#cb11-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-61"><a href="#cb11-61" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb11-62"><a href="#cb11-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-63"><a href="#cb11-63" aria-hidden="true" tabindex="-1"></a>::: {.callout-note title="Fase 3: Enseñanza en el grupo original (2 x 5 minutos)"}</span>
<span id="cb11-64"><a href="#cb11-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-65"><a href="#cb11-65" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>Cada experto regresa a su grupo original y enseña a los demás miembros del grupo sobre su tema.</span>
<span id="cb11-66"><a href="#cb11-66" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>Se discuten y resuelven dudas sobre los temas presentados por los expertos.</span>
<span id="cb11-67"><a href="#cb11-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-68"><a href="#cb11-68" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb11-69"><a href="#cb11-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-70"><a href="#cb11-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-71"><a href="#cb11-71" aria-hidden="true" tabindex="-1"></a>::: {.callout-note title="Fase 4: Reflexión y cierre (5 minutos)"}</span>
<span id="cb11-72"><a href="#cb11-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-73"><a href="#cb11-73" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>Se comparten conclusiones y se resuelven dudas finales con toda la clase.</span>
<span id="cb11-74"><a href="#cb11-74" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>Cada grupo original (no grupo de expertos) tiene que resolver la tarea de la ultima página (caja roja).</span>
<span id="cb11-75"><a href="#cb11-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-76"><a href="#cb11-76" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb11-77"><a href="#cb11-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-78"><a href="#cb11-78" aria-hidden="true" tabindex="-1"></a>**El reporte de Fase 2, escrito en su bitacora, representa su entrada de bitacora calificada**</span>
<span id="cb11-79"><a href="#cb11-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-80"><a href="#cb11-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-81"><a href="#cb11-81" aria-hidden="true" tabindex="-1"></a><span class="in">```{=latex}</span></span>
<span id="cb11-82"><a href="#cb11-82" aria-hidden="true" tabindex="-1"></a><span class="in">\normalsize</span></span>
<span id="cb11-83"><a href="#cb11-83" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-84"><a href="#cb11-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-85"><a href="#cb11-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-86"><a href="#cb11-86" aria-hidden="true" tabindex="-1"></a>{{&lt; pagebreak &gt;}}</span>
<span id="cb11-87"><a href="#cb11-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-88"><a href="#cb11-88" aria-hidden="true" tabindex="-1"></a><span class="fu">## Material</span></span>
<span id="cb11-89"><a href="#cb11-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-90"><a href="#cb11-90" aria-hidden="true" tabindex="-1"></a>En lo que sigue se presentan los conceptos básicos de los modelos lineales (<span class="in">`lm()`</span>) y cómo interpretar </span>
<span id="cb11-91"><a href="#cb11-91" aria-hidden="true" tabindex="-1"></a>su salida. Todos los ejemplos usan el dataset <span class="in">`iris`</span>, incluido con <span class="in">`R`</span>.</span>
<span id="cb11-92"><a href="#cb11-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-93"><a href="#cb11-93" aria-hidden="true" tabindex="-1"></a><span class="fu">## Conceptos básicos de regresión lineal (todos)</span></span>
<span id="cb11-94"><a href="#cb11-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-95"><a href="#cb11-95" aria-hidden="true" tabindex="-1"></a>Un modelo lineal describe una variable respuesta continua (<span class="in">`y`</span>) en función de uno o más predictores (<span class="in">`x`</span>):</span>
<span id="cb11-96"><a href="#cb11-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-97"><a href="#cb11-97" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>Los predictores pueden ser **continuos** (una pendiente) o **categóricos** (diferencias entre grupos).</span>
<span id="cb11-98"><a href="#cb11-98" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span><span class="in">`lm()`</span> ajusta el modelo; <span class="in">`summary()`</span> muestra los coeficientes estimados, su incertidumbre y pruebas asociadas.</span>
<span id="cb11-99"><a href="#cb11-99" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>Supuestos del modelo: </span>
<span id="cb11-100"><a href="#cb11-100" aria-hidden="true" tabindex="-1"></a><span class="ss">    * </span>relación lineal -- la relación entre los predictores y la respuesta debe ser aproximadamente lineal.  </span>
<span id="cb11-101"><a href="#cb11-101" aria-hidden="true" tabindex="-1"></a><span class="ss">    * </span>residuos normales -- los residuos del modelo deben seguir aproximadamente una distribución normal.  </span>
<span id="cb11-102"><a href="#cb11-102" aria-hidden="true" tabindex="-1"></a><span class="ss">    * </span>varianza constante (homocedasticidad) -- la dispersión de los residuos debe ser similar a lo largo de todos los valores predichos.  </span>
<span id="cb11-103"><a href="#cb11-103" aria-hidden="true" tabindex="-1"></a><span class="ss">    * </span>independencia -- los residuos deben ser independientes entre sí, sin correlación.  </span>
<span id="cb11-104"><a href="#cb11-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-105"><a href="#cb11-105" aria-hidden="true" tabindex="-1"></a><span class="in">```r</span></span>
<span id="cb11-106"><a href="#cb11-106" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x, <span class="at">data =</span> datos)</span>
<span id="cb11-107"><a href="#cb11-107" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo)</span>
<span id="cb11-108"><a href="#cb11-108" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-109"><a href="#cb11-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-110"><a href="#cb11-110" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span><span class="in">`y`</span>: variable respuesta del modelo.</span>
<span id="cb11-111"><a href="#cb11-111" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span><span class="in">`x`</span>: predictor del modelo; puede haber cualquier número de predictores, continuos o categóricos.</span>
<span id="cb11-112"><a href="#cb11-112" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>Los predictores se combinan con <span class="in">`+`</span> para incluirlos de manera aditiva en el modelo.</span>
<span id="cb11-113"><a href="#cb11-113" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>Con <span class="in">`+`</span>, el modelo incluye los efectos de los predictores de manera aditiva, sin términos de interacción.</span>
<span id="cb11-114"><a href="#cb11-114" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>Para incluir interacciones entre predictores, se usa <span class="in">`*`</span> (por ejemplo, <span class="in">`x1 * x2`</span>). En este caso el modelo considera tanto los efectos principales como la interacción entre <span class="in">`x1`</span> y <span class="in">`x2`</span>.</span>
<span id="cb11-115"><a href="#cb11-115" aria-hidden="true" tabindex="-1"></a><span class="ss">  * </span>La interacción permite que el efecto de un predictor dependa del valor de otro predictor.</span>
<span id="cb11-116"><a href="#cb11-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-117"><a href="#cb11-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-118"><a href="#cb11-118" aria-hidden="true" tabindex="-1"></a>{{&lt; pagebreak &gt;}}</span>
<span id="cb11-119"><a href="#cb11-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-120"><a href="#cb11-120" aria-hidden="true" tabindex="-1"></a><span class="fu">## Resumen de un modelo lineal con un predictor continuo (experto 1)</span></span>
<span id="cb11-121"><a href="#cb11-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-122"><a href="#cb11-122" aria-hidden="true" tabindex="-1"></a><span class="in">```r</span></span>
<span id="cb11-123"><a href="#cb11-123" aria-hidden="true" tabindex="-1"></a>modelo_continuo <span class="ot">&lt;-</span> <span class="fu">lm</span>(Petal.Length <span class="sc">~</span> Sepal.Length, <span class="at">data =</span> iris)</span>
<span id="cb11-124"><a href="#cb11-124" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-125"><a href="#cb11-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-126"><a href="#cb11-126" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>**Estimate** (<span class="in">`(Intercept)`</span> y pendiente): valor esperado de <span class="in">`y`</span> cuando <span class="in">`x = 0`</span>, y cambio en <span class="in">`y`</span> por cada unidad de <span class="in">`x`</span>.</span>
<span id="cb11-127"><a href="#cb11-127" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>**Std. Error / t value / Pr(&gt;|t|)**: incertidumbre del coeficiente y prueba de si es diferente de cero.</span>
<span id="cb11-128"><a href="#cb11-128" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>**R² / R² ajustado**: proporción de la varianza de <span class="in">`y`</span> explicada por el modelo.</span>
<span id="cb11-129"><a href="#cb11-129" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>**F-statistic y su p-value**: prueba si el modelo en conjunto explica más que el modelo nulo (solo el intercepto).</span>
<span id="cb11-130"><a href="#cb11-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-133"><a href="#cb11-133" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb11-134"><a href="#cb11-134" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb11-135"><a href="#cb11-135" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_continuo)</span>
<span id="cb11-136"><a href="#cb11-136" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-137"><a href="#cb11-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-138"><a href="#cb11-138" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip title="Como calcular la ecuación del modelo y intervalos de confianza" }</span>
<span id="cb11-139"><a href="#cb11-139" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb11-140"><a href="#cb11-140" aria-hidden="true" tabindex="-1"></a>\quad y = \text{intercept} + \text{coef(Sepal.Length)} \cdot x = -7.1014 + 1.8584x</span>
<span id="cb11-141"><a href="#cb11-141" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb11-142"><a href="#cb11-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-143"><a href="#cb11-143" aria-hidden="true" tabindex="-1"></a>Los intervalos de confianza proporcionan un rango de valores plausibles para cada coeficiente del modelo. Si un intervalo incluye el valor cero, sugiere que el coeficiente podría no ser significativamente diferente de cero. Se pueden calcular con:</span>
<span id="cb11-144"><a href="#cb11-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-145"><a href="#cb11-145" aria-hidden="true" tabindex="-1"></a><span class="in">```r</span></span>
<span id="cb11-146"><a href="#cb11-146" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(modelo_continuo)</span>
<span id="cb11-147"><a href="#cb11-147" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-148"><a href="#cb11-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-149"><a href="#cb11-149" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb11-150"><a href="#cb11-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-151"><a href="#cb11-151" aria-hidden="true" tabindex="-1"></a>{{&lt; pagebreak &gt;}}</span>
<span id="cb11-152"><a href="#cb11-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-153"><a href="#cb11-153" aria-hidden="true" tabindex="-1"></a><span class="fu">## Resumen de un modelo lineal con un predictor categórico (experto 2)</span></span>
<span id="cb11-154"><a href="#cb11-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-155"><a href="#cb11-155" aria-hidden="true" tabindex="-1"></a><span class="in">```r</span></span>
<span id="cb11-156"><a href="#cb11-156" aria-hidden="true" tabindex="-1"></a>modelo_categorico <span class="ot">&lt;-</span> <span class="fu">lm</span>(Petal.Length <span class="sc">~</span> Species, <span class="at">data =</span> iris)</span>
<span id="cb11-157"><a href="#cb11-157" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-158"><a href="#cb11-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-159"><a href="#cb11-159" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>R utiliza el **primer nivel del factor** como nivel de referencia (en <span class="in">`iris`</span>, <span class="in">`setosa`</span>), que queda absorbido en el <span class="in">`(Intercept)`</span>.</span>
<span id="cb11-160"><a href="#cb11-160" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>**`(Intercept)`**: valor promedio de <span class="in">`y`</span> para el nivel de referencia.</span>
<span id="cb11-161"><a href="#cb11-161" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>**Coeficientes de los otros niveles**: diferencia promedio respecto al nivel de referencia, no el valor absoluto del grupo.</span>
<span id="cb11-162"><a href="#cb11-162" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>**R² / F-statistic**: mismos conceptos que con predictor continuo, aplicados a la comparación entre grupos.</span>
<span id="cb11-163"><a href="#cb11-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-166"><a href="#cb11-166" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb11-167"><a href="#cb11-167" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb11-168"><a href="#cb11-168" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_categorico)</span>
<span id="cb11-169"><a href="#cb11-169" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-170"><a href="#cb11-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-171"><a href="#cb11-171" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip title="Como calcular el promedio de cada nivel" }</span>
<span id="cb11-172"><a href="#cb11-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-173"><a href="#cb11-173" aria-hidden="true" tabindex="-1"></a>*setosa*:</span>
<span id="cb11-174"><a href="#cb11-174" aria-hidden="true" tabindex="-1"></a>$$ \quad \bar{y} = \text{intercept} = 1.462 $$</span>
<span id="cb11-175"><a href="#cb11-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-176"><a href="#cb11-176" aria-hidden="true" tabindex="-1"></a>*versicolor*:</span>
<span id="cb11-177"><a href="#cb11-177" aria-hidden="true" tabindex="-1"></a>$$ \quad \bar{y} = \text{intercept} + \text{coef(versicolor)} = 1.462 + 2.798 = 4.260 $$</span>
<span id="cb11-178"><a href="#cb11-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-179"><a href="#cb11-179" aria-hidden="true" tabindex="-1"></a>*virginica*:</span>
<span id="cb11-180"><a href="#cb11-180" aria-hidden="true" tabindex="-1"></a>$$ \quad \bar{y} = \text{intercept} + \text{coef(virginica)} = 1.462 + 4.090 = 5.552 $$</span>
<span id="cb11-181"><a href="#cb11-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-182"><a href="#cb11-182" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb11-183"><a href="#cb11-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-184"><a href="#cb11-184" aria-hidden="true" tabindex="-1"></a>{{&lt; pagebreak &gt;}}</span>
<span id="cb11-185"><a href="#cb11-185" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-186"><a href="#cb11-186" aria-hidden="true" tabindex="-1"></a><span class="fu">## Resumen (`summary()`) de un modelo lineal con dos predictores y su interacción (experto 3)</span></span>
<span id="cb11-187"><a href="#cb11-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-188"><a href="#cb11-188" aria-hidden="true" tabindex="-1"></a><span class="in">```r</span></span>
<span id="cb11-189"><a href="#cb11-189" aria-hidden="true" tabindex="-1"></a>modelo_interaccion <span class="ot">&lt;-</span> <span class="fu">lm</span>(Petal.Length <span class="sc">~</span> Sepal.Length <span class="sc">*</span> Species, <span class="at">data =</span> iris)</span>
<span id="cb11-190"><a href="#cb11-190" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-191"><a href="#cb11-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-192"><a href="#cb11-192" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span><span class="in">`(Intercept)`</span>: intercepto del nivel de referencia (setosa).</span>
<span id="cb11-193"><a href="#cb11-193" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span><span class="in">`Sepal.Length`</span>: pendiente para el nivel de referencia.</span>
<span id="cb11-194"><a href="#cb11-194" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span><span class="in">`Speciesversicolor`</span>, <span class="in">`Speciesvirginica`</span>: diferencias en el intercepto respecto al nivel de referencia.</span>
<span id="cb11-195"><a href="#cb11-195" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span><span class="in">`Términos de interacción`</span>: diferencias en la pendiente respecto al nivel de referencia.</span>
<span id="cb11-196"><a href="#cb11-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-199"><a href="#cb11-199" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb11-200"><a href="#cb11-200" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb11-201"><a href="#cb11-201" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_interaccion)</span>
<span id="cb11-202"><a href="#cb11-202" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-203"><a href="#cb11-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-204"><a href="#cb11-204" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip title="Como calcular los efectos de cada nivel de la interacción" }</span>
<span id="cb11-205"><a href="#cb11-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-206"><a href="#cb11-206" aria-hidden="true" tabindex="-1"></a>*setosa*:</span>
<span id="cb11-207"><a href="#cb11-207" aria-hidden="true" tabindex="-1"></a>$$ \quad y_{\text{setosa}}=\text{intercept}+\text{coef(Sepal.Length)}\cdot x $$</span>
<span id="cb11-208"><a href="#cb11-208" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!-- $$ \quad y=0.8031+0.1316x $$ --&gt;</span></span>
<span id="cb11-209"><a href="#cb11-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-210"><a href="#cb11-210" aria-hidden="true" tabindex="-1"></a>*versicolor*:</span>
<span id="cb11-211"><a href="#cb11-211" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb11-212"><a href="#cb11-212" aria-hidden="true" tabindex="-1"></a>\begin{aligned}</span>
<span id="cb11-213"><a href="#cb11-213" aria-hidden="true" tabindex="-1"></a>\quad y &amp;= \text{intercept}+\text{coef(versicolor)}+ <span class="sc">\\</span></span>
<span id="cb11-214"><a href="#cb11-214" aria-hidden="true" tabindex="-1"></a>&amp;\quad \big(\text{coef(Sepal.Length)}+\text{coef(Sepal.Length:Speciesversicolor)}\big)\cdot x</span>
<span id="cb11-215"><a href="#cb11-215" aria-hidden="true" tabindex="-1"></a>\end{aligned}</span>
<span id="cb11-216"><a href="#cb11-216" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb11-217"><a href="#cb11-217" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!-- $$ \quad y = (0.8031-0.6179) + (0.1316+0.5548)x $$ --&gt;</span></span>
<span id="cb11-218"><a href="#cb11-218" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-219"><a href="#cb11-219" aria-hidden="true" tabindex="-1"></a>*virginica*:</span>
<span id="cb11-220"><a href="#cb11-220" aria-hidden="true" tabindex="-1"></a>$$\begin{aligned}</span>
<span id="cb11-221"><a href="#cb11-221" aria-hidden="true" tabindex="-1"></a>\quad y &amp;= \text{intercept}+\text{coef(virginica)}+ <span class="sc">\\</span></span>
<span id="cb11-222"><a href="#cb11-222" aria-hidden="true" tabindex="-1"></a>&amp;\quad \big(\text{coef(Sepal.Length)}+\text{coef(Sepal.Length:Speciesvirginica)}\big)\cdot x</span>
<span id="cb11-223"><a href="#cb11-223" aria-hidden="true" tabindex="-1"></a>\end{aligned}$$</span>
<span id="cb11-224"><a href="#cb11-224" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!-- $$\quad y = (0.8031-0.1926) + (0.1316+0.6184)x $$ --&gt;</span></span>
<span id="cb11-225"><a href="#cb11-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-226"><a href="#cb11-226" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb11-227"><a href="#cb11-227" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-228"><a href="#cb11-228" aria-hidden="true" tabindex="-1"></a>{{&lt; pagebreak &gt;}}</span>
<span id="cb11-229"><a href="#cb11-229" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-230"><a href="#cb11-230" aria-hidden="true" tabindex="-1"></a><span class="fu">## Diagnósticos gráficos I: linealidad y normalidad (experto 4)</span></span>
<span id="cb11-231"><a href="#cb11-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-232"><a href="#cb11-232" aria-hidden="true" tabindex="-1"></a><span class="in">```r</span></span>
<span id="cb11-233"><a href="#cb11-233" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(modelo_interaccion, <span class="at">which =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb11-234"><a href="#cb11-234" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-235"><a href="#cb11-235" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-236"><a href="#cb11-236" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>**Residuals vs Fitted**: busca patrones o curvatura; una nube sin forma clara indica que la relación es razonablemente lineal.</span>
<span id="cb11-237"><a href="#cb11-237" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>**Normal Q-Q**: los puntos deben seguir aproximadamente la línea diagonal; desviaciones fuertes en los extremos sugieren residuos no normales.</span>
<span id="cb11-238"><a href="#cb11-238" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>Juntos, estos dos gráficos dicen si un modelo lineal es una descripción razonable de los datos.</span>
<span id="cb11-239"><a href="#cb11-239" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-242"><a href="#cb11-242" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb11-243"><a href="#cb11-243" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb11-244"><a href="#cb11-244" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 4</span></span>
<span id="cb11-245"><a href="#cb11-245" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-width: 9</span></span>
<span id="cb11-246"><a href="#cb11-246" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb11-247"><a href="#cb11-247" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(modelo_interaccion, <span class="at">which =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb11-248"><a href="#cb11-248" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-249"><a href="#cb11-249" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-250"><a href="#cb11-250" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip title="Mas info" }</span>
<span id="cb11-251"><a href="#cb11-251" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-252"><a href="#cb11-252" aria-hidden="true" tabindex="-1"></a>**Residuals vs Fitted**  </span>
<span id="cb11-253"><a href="#cb11-253" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-254"><a href="#cb11-254" aria-hidden="true" tabindex="-1"></a>Los residuos deberían distribuirse de manera aleatoria alrededor de cero. Algun patron sistemático indica que </span>
<span id="cb11-255"><a href="#cb11-255" aria-hidden="true" tabindex="-1"></a>el modelo puede no estar capturando toda la estructura de los datos. Por ejemplo, un patrón en forma de </span>
<span id="cb11-256"><a href="#cb11-256" aria-hidden="true" tabindex="-1"></a>"banano" sugiere que falta una transformación (por ejemplo, logarítmica) o un término no lineal.</span>
<span id="cb11-257"><a href="#cb11-257" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-258"><a href="#cb11-258" aria-hidden="true" tabindex="-1"></a>**Normal Q-Q**  </span>
<span id="cb11-259"><a href="#cb11-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-260"><a href="#cb11-260" aria-hidden="true" tabindex="-1"></a>Con muestras grandes, el modelo lineal es bastante robusto a desviaciones leves de normalidad, </span>
<span id="cb11-261"><a href="#cb11-261" aria-hidden="true" tabindex="-1"></a>así que un Q-Q plot "casi" recto, aunque no perfecto, muchas veces suele bastar. i.e., muchas </span>
<span id="cb11-262"><a href="#cb11-262" aria-hidden="true" tabindex="-1"></a>veces no es necesario 'hacer algo' para para que todos los residuos quedan perfectamente en la línea.</span>
<span id="cb11-263"><a href="#cb11-263" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-264"><a href="#cb11-264" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb11-265"><a href="#cb11-265" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-266"><a href="#cb11-266" aria-hidden="true" tabindex="-1"></a>{{&lt; pagebreak &gt;}}</span>
<span id="cb11-267"><a href="#cb11-267" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-268"><a href="#cb11-268" aria-hidden="true" tabindex="-1"></a><span class="fu">## Diagnósticos gráficos II: varianza y observaciones influyentes (experto 5)</span></span>
<span id="cb11-269"><a href="#cb11-269" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-270"><a href="#cb11-270" aria-hidden="true" tabindex="-1"></a><span class="in">```r</span></span>
<span id="cb11-271"><a href="#cb11-271" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(modelo_interaccion, <span class="at">which =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">5</span>))</span>
<span id="cb11-272"><a href="#cb11-272" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-273"><a href="#cb11-273" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-274"><a href="#cb11-274" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>**Scale-Location**: la línea debería ser aproximadamente horizontal, con dispersión pareja; una forma de embudo indica que la varianza no es constante (heterocedasticidad).</span>
<span id="cb11-275"><a href="#cb11-275" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>**Residuals vs Leverage**: identifica observaciones con mucha influencia sobre el modelo; puntos con una distancia de Cook alta pueden tener una influencia importante sobre los coeficientes del modelo.</span>
<span id="cb11-276"><a href="#cb11-276" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>Estos dos gráficos ayudan a decidir si algunas observaciones particulares merecen atención (errores de datos, casos atípicos reales).</span>
<span id="cb11-277"><a href="#cb11-277" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-280"><a href="#cb11-280" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb11-281"><a href="#cb11-281" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb11-282"><a href="#cb11-282" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 4</span></span>
<span id="cb11-283"><a href="#cb11-283" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-width: 9</span></span>
<span id="cb11-284"><a href="#cb11-284" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb11-285"><a href="#cb11-285" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(modelo_interaccion, <span class="at">which =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">5</span>))</span>
<span id="cb11-286"><a href="#cb11-286" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-287"><a href="#cb11-287" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-288"><a href="#cb11-288" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip title="Mas info" }</span>
<span id="cb11-289"><a href="#cb11-289" aria-hidden="true" tabindex="-1"></a>**Distancia cook**  </span>
<span id="cb11-290"><a href="#cb11-290" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb11-291"><a href="#cb11-291" aria-hidden="true" tabindex="-1"></a>La distancia de Cook depende de los valores de leverage y de los residuos de cada observación. Una distancia de Cook alta indica que la observación puede tener una influencia importante sobre los coeficientes del modelo.  </span>
<span id="cb11-292"><a href="#cb11-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-293"><a href="#cb11-293" aria-hidden="true" tabindex="-1"></a>Las líneas punteadas de distancia de Cook solo se dibujan si caen dentro del rango visible del gráfico. </span>
<span id="cb11-294"><a href="#cb11-294" aria-hidden="true" tabindex="-1"></a>Si las líneas de referencia de Cook quedan fuera del rango del gráfico, pueden no aparecer; esto no indica un error del gráfico.  </span>
<span id="cb11-295"><a href="#cb11-295" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb11-296"><a href="#cb11-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-297"><a href="#cb11-297" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-298"><a href="#cb11-298" aria-hidden="true" tabindex="-1"></a>{{&lt; pagebreak &gt;}}</span>
<span id="cb11-299"><a href="#cb11-299" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-300"><a href="#cb11-300" aria-hidden="true" tabindex="-1"></a>::: {.callout-important title="Tarea (Fase 4)"}</span>
<span id="cb11-301"><a href="#cb11-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-302"><a href="#cb11-302" aria-hidden="true" tabindex="-1"></a>**Cada grupo original (no grupo de expertos) analiza los mismos datos `iris` en su computadora.**  </span>
<span id="cb11-303"><a href="#cb11-303" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-304"><a href="#cb11-304" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Pregunta biológica: ¿cómo cambia el ancho del pétalo con el ancho del sépalo y ese cambio es distinto entre especies?</span></span>
<span id="cb11-305"><a href="#cb11-305" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-306"><a href="#cb11-306" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Ajusten </span></span>
<span id="cb11-307"><a href="#cb11-307" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;  * un modelo con interceptos diferentes entre especies y una pendiente común para todas las especies, y </span></span>
<span id="cb11-308"><a href="#cb11-308" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;  * otro que permita intercepto y pendiente distinta por especie. </span></span>
<span id="cb11-309"><a href="#cb11-309" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb11-310"><a href="#cb11-310" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Extraigan los coeficientes y sus intervalos de confianza. Comparen los modelos con AIC e interpreten los resultados.</span></span>
<span id="cb11-311"><a href="#cb11-311" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-312"><a href="#cb11-312" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Tareas:</span></span>
<span id="cb11-313"><a href="#cb11-313" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span></span>
<span id="cb11-314"><a href="#cb11-314" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;   * Ajusten los dos modelos y comparen sus valores de AIC.</span></span>
<span id="cb11-315"><a href="#cb11-315" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;   * Usen </span><span class="in">`coef()`</span><span class="at"> y </span><span class="in">`confint()`</span><span class="at"> para identificar el tamaño y la incertidumbre de los efectos de </span><span class="in">`Sepal.Width`</span><span class="at">, de las especies y de los términos de interacción.</span></span>
<span id="cb11-316"><a href="#cb11-316" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;   * En el modelo con interacción, los coeficientes de especie representan diferencias en el intercepto cuando </span><span class="in">`Sepal.Width = 0`</span><span class="at">.</span></span>
<span id="cb11-317"><a href="#cb11-317" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;   * Escriban un párrafo que responda la pregunta biológica. Describan la dirección y magnitud de los efectos, e indiquen los intervalos de confianza.</span></span>
<span id="cb11-318"><a href="#cb11-318" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;   * Usen los *p-values* solo como información complementaria. La interpretación principal debe basarse en los tamaños de efecto, sus intervalos de confianza y el apoyo relativo de los modelos según AIC.</span></span>
<span id="cb11-319"><a href="#cb11-319" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-320"><a href="#cb11-320" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Para el análisis, usen </span><span class="in">`lm()`</span><span class="at">, </span><span class="in">`summary()`</span><span class="at">, </span><span class="in">`coef()`</span><span class="at">, </span><span class="in">`confint()`</span><span class="at"> y </span><span class="in">`AIC()`</span><span class="at">.</span></span>
<span id="cb11-321"><a href="#cb11-321" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-322"><a href="#cb11-322" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Nota: un AIC menor indica un mejor balance entre ajuste y complejidad. Modelos con valores de AIC muy similares (por ejemplo, $\Delta\mathrm{AIC} &lt; 2$) suelen tener apoyo comparable; diferencias mayores favorecen al modelo con el menor AIC.</span></span>
<span id="cb11-323"><a href="#cb11-323" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-324"><a href="#cb11-324" aria-hidden="true" tabindex="-1"></a>:::</span>
</code><button title="Copiar al portapapeles" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>